#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  anon_sym_DOT = 1,
  anon_sym_COMMA = 2,
  anon_sym_COLON_COLON = 3,
  anon_sym_COLON_DASH = 4,
  anon_sym_QMARK_DASH = 5,
  anon_sym_RBRACK = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  sym_false = 9,
  sym_true = 10,
  anon_sym_BSLASH = 11,
  anon_sym_EQ_GT = 12,
  anon_sym_BSLASH_SLASH = 13,
  anon_sym_SLASH_BSLASH = 14,
  anon_sym_TILDE = 15,
  anon_sym_not = 16,
  anon_sym_EQ = 17,
  anon_sym_COLON = 18,
  sym_type_i = 19,
  sym_type_o = 20,
  anon_sym_DASH_GT = 21,
  sym_const = 22,
  sym_var = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym__sentence = 26,
  sym_typing_declaration = 27,
  sym_clause = 28,
  sym_fact = 29,
  sym_query = 30,
  sym__head = 31,
  sym_body = 32,
  sym_existential_body = 33,
  sym__parameters = 34,
  sym__expression = 35,
  sym__atom = 36,
  sym__expression_i = 37,
  sym_application = 38,
  sym_lambda = 39,
  sym_or = 40,
  sym_and = 41,
  sym_not = 42,
  sym_eq = 43,
  sym_exists = 44,
  sym_typed_var = 45,
  sym__type = 46,
  sym_type_arrow = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_typing_declaration_repeat1 = 49,
  aux_sym_body_repeat1 = 50,
  aux_sym__parameters_repeat1 = 51,
  aux_sym__parameters_repeat2 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_QMARK_DASH] = "\?-",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_false] = "false",
  [sym_true] = "true",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_BSLASH_SLASH] = "\\/",
  [anon_sym_SLASH_BSLASH] = "/\\",
  [anon_sym_TILDE] = "~",
  [anon_sym_not] = "not",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [sym_type_i] = "type_i",
  [sym_type_o] = "type_o",
  [anon_sym_DASH_GT] = "->",
  [sym_const] = "const",
  [sym_var] = "var",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__sentence] = "_sentence",
  [sym_typing_declaration] = "typing_declaration",
  [sym_clause] = "clause",
  [sym_fact] = "fact",
  [sym_query] = "query",
  [sym__head] = "_head",
  [sym_body] = "body",
  [sym_existential_body] = "existential_body",
  [sym__parameters] = "_parameters",
  [sym__expression] = "_expression",
  [sym__atom] = "_atom",
  [sym__expression_i] = "_expression_i",
  [sym_application] = "application",
  [sym_lambda] = "lambda",
  [sym_or] = "or",
  [sym_and] = "and",
  [sym_not] = "not",
  [sym_eq] = "eq",
  [sym_exists] = "exists",
  [sym_typed_var] = "typed_var",
  [sym__type] = "_type",
  [sym_type_arrow] = "type_arrow",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_typing_declaration_repeat1] = "typing_declaration_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym__parameters_repeat1] = "_parameters_repeat1",
  [aux_sym__parameters_repeat2] = "_parameters_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_QMARK_DASH] = anon_sym_QMARK_DASH,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_false] = sym_false,
  [sym_true] = sym_true,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_BSLASH_SLASH] = anon_sym_BSLASH_SLASH,
  [anon_sym_SLASH_BSLASH] = anon_sym_SLASH_BSLASH,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_type_i] = sym_type_i,
  [sym_type_o] = sym_type_o,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_const] = sym_const,
  [sym_var] = sym_var,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__sentence] = sym__sentence,
  [sym_typing_declaration] = sym_typing_declaration,
  [sym_clause] = sym_clause,
  [sym_fact] = sym_fact,
  [sym_query] = sym_query,
  [sym__head] = sym__head,
  [sym_body] = sym_body,
  [sym_existential_body] = sym_existential_body,
  [sym__parameters] = sym__parameters,
  [sym__expression] = sym__expression,
  [sym__atom] = sym__atom,
  [sym__expression_i] = sym__expression_i,
  [sym_application] = sym_application,
  [sym_lambda] = sym_lambda,
  [sym_or] = sym_or,
  [sym_and] = sym_and,
  [sym_not] = sym_not,
  [sym_eq] = sym_eq,
  [sym_exists] = sym_exists,
  [sym_typed_var] = sym_typed_var,
  [sym__type] = sym__type,
  [sym_type_arrow] = sym_type_arrow,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_typing_declaration_repeat1] = aux_sym_typing_declaration_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym__parameters_repeat1] = aux_sym__parameters_repeat1,
  [aux_sym__parameters_repeat2] = aux_sym__parameters_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_false] = {
    .visible = true,
    .named = true,
  },
  [sym_true] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_type_i] = {
    .visible = true,
    .named = true,
  },
  [sym_type_o] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_const] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__sentence] = {
    .visible = false,
    .named = true,
  },
  [sym_typing_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_fact] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym__head] = {
    .visible = false,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_existential_body] = {
    .visible = true,
    .named = true,
  },
  [sym__parameters] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym__expression_i] = {
    .visible = false,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_not] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_exists] = {
    .visible = true,
    .named = true,
  },
  [sym_typed_var] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_type_arrow] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typing_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__parameters_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_parameters = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_parameters] = "parameters",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_parameters, 0, .inherited = true},
  [1] =
    {field_parameters, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '%', 59,
        '(', 25,
        ')', 26,
        ',', 20,
        '-', 5,
        '.', 19,
        '/', 7,
        ':', 42,
        '=', 40,
        '?', 4,
        '\\', 32,
        ']', 24,
        'f', 8,
        'i', 43,
        'n', 12,
        'o', 44,
        't', 13,
        '~', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '%', 59,
        '(', 25,
        ')', 26,
        ',', 20,
        '.', 19,
        '/', 7,
        ':', 41,
        '=', 39,
        '\\', 32,
        ']', 24,
        'f', 47,
        'n', 51,
        't', 52,
        '~', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '%', 59,
        '(', 25,
        ')', 26,
        '-', 5,
        '.', 19,
        ':', 41,
        '=', 6,
        '\\', 31,
        ']', 24,
        'f', 47,
        'n', 51,
        't', 52,
        '~', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '\\') ADVANCE(35);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '%') ADVANCE(59);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '?') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_QMARK_DASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_false);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_false);
      if (lookahead == '\'') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_true);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_true);
      if (lookahead == '\'') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BSLASH_SLASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_BSLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_not);
      if (lookahead == '\'') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(21);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_type_i);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_type_o);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 'a') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 'l') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 'o') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 'r') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 's') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 't') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == 'u') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_const);
      if (lookahead == '\'') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_var);
      if (lookahead == '\'') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_var);
      if (lookahead == '\'') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(59);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 17},
  [36] = {.lex_state = 17},
  [37] = {.lex_state = 17},
  [38] = {.lex_state = 17},
  [39] = {.lex_state = 17},
  [40] = {.lex_state = 17},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 17},
  [48] = {.lex_state = 17},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 17},
  [51] = {.lex_state = 17},
  [52] = {.lex_state = 17},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 17},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 17},
  [66] = {.lex_state = 17},
  [67] = {.lex_state = 17},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 17},
  [70] = {.lex_state = 17},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 17},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 17},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_QMARK_DASH] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_false] = ACTIONS(1),
    [sym_true] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_BSLASH_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_BSLASH] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_type_i] = ACTIONS(1),
    [sym_type_o] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_var] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(74),
    [sym__sentence] = STATE(77),
    [sym_typing_declaration] = STATE(77),
    [sym_clause] = STATE(77),
    [sym_fact] = STATE(77),
    [sym_query] = STATE(77),
    [sym__head] = STATE(70),
    [aux_sym_source_file_repeat1] = STATE(35),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_QMARK_DASH] = ACTIONS(7),
    [sym_const] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(13), 5,
      sym_false,
      sym_true,
      anon_sym_BSLASH,
      anon_sym_not,
      sym_const,
    ACTIONS(11), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
      anon_sym_TILDE,
      sym_var,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [36] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    ACTIONS(15), 5,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [86] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(33), 1,
      anon_sym_DOT,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_BSLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    STATE(57), 1,
      aux_sym_body_repeat1,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [144] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(33), 1,
      anon_sym_DOT,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_BSLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    STATE(57), 1,
      aux_sym_body_repeat1,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [202] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_BSLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_body_repeat1,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [260] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(37), 1,
      anon_sym_BSLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    ACTIONS(43), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [314] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(37), 1,
      anon_sym_BSLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    ACTIONS(45), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [368] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    ACTIONS(47), 5,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [418] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    ACTIONS(49), 4,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [470] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(37), 1,
      anon_sym_BSLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    ACTIONS(51), 3,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [524] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    ACTIONS(61), 1,
      anon_sym_COLON,
    STATE(76), 1,
      sym_body,
    STATE(80), 1,
      sym__expression_i,
    STATE(82), 1,
      sym_existential_body,
    ACTIONS(57), 2,
      sym_false,
      sym_true,
    STATE(5), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [576] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(37), 1,
      anon_sym_BSLASH_SLASH,
    ACTIONS(39), 1,
      anon_sym_SLASH_BSLASH,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(21), 2,
      sym_false,
      sym_true,
    STATE(2), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [628] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(76), 1,
      sym_body,
    STATE(80), 1,
      sym__expression_i,
    STATE(82), 1,
      sym_existential_body,
    ACTIONS(57), 2,
      sym_false,
      sym_true,
    STATE(5), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [677] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(79), 1,
      sym_body,
    STATE(80), 1,
      sym__expression_i,
    STATE(82), 1,
      sym_existential_body,
    ACTIONS(65), 2,
      sym_false,
      sym_true,
    STATE(4), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [726] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    STATE(81), 1,
      sym_body,
    STATE(82), 1,
      sym_existential_body,
    ACTIONS(65), 2,
      sym_false,
      sym_true,
    STATE(4), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [775] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    ACTIONS(61), 1,
      anon_sym_COLON,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(67), 2,
      sym_false,
      sym_true,
    STATE(7), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [821] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(69), 2,
      sym_false,
      sym_true,
    STATE(3), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [864] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(71), 2,
      sym_false,
      sym_true,
    STATE(8), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [907] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(73), 2,
      sym_false,
      sym_true,
    STATE(6), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [950] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(75), 2,
      sym_false,
      sym_true,
    STATE(9), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [993] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(77), 2,
      sym_false,
      sym_true,
    STATE(10), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [1036] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(79), 2,
      sym_false,
      sym_true,
    STATE(13), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [1079] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(67), 2,
      sym_false,
      sym_true,
    STATE(7), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [1122] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 1,
      anon_sym_TILDE,
    ACTIONS(27), 1,
      anon_sym_not,
    ACTIONS(29), 1,
      sym_const,
    ACTIONS(31), 1,
      sym_var,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    ACTIONS(59), 1,
      anon_sym_BSLASH,
    STATE(80), 1,
      sym__expression_i,
    ACTIONS(81), 2,
      sym_false,
      sym_true,
    STATE(11), 9,
      sym__expression,
      sym__atom,
      sym_application,
      sym_lambda,
      sym_or,
      sym_and,
      sym_not,
      sym_eq,
      sym_exists,
  [1165] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_EQ,
    ACTIONS(85), 5,
      sym_false,
      sym_true,
      anon_sym_BSLASH,
      anon_sym_not,
      sym_const,
    ACTIONS(83), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
      anon_sym_TILDE,
      sym_var,
  [1190] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 5,
      sym_false,
      sym_true,
      anon_sym_BSLASH,
      anon_sym_not,
      sym_const,
    ACTIONS(89), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
      anon_sym_TILDE,
      sym_var,
  [1212] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 5,
      sym_false,
      sym_true,
      anon_sym_BSLASH,
      anon_sym_not,
      sym_const,
    ACTIONS(93), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
      anon_sym_TILDE,
      sym_var,
  [1234] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 5,
      sym_false,
      sym_true,
      anon_sym_BSLASH,
      anon_sym_not,
      sym_const,
    ACTIONS(97), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
      anon_sym_TILDE,
      sym_var,
  [1256] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 5,
      sym_false,
      sym_true,
      anon_sym_BSLASH,
      anon_sym_not,
      sym_const,
    ACTIONS(101), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH_SLASH,
      anon_sym_SLASH_BSLASH,
      anon_sym_TILDE,
      sym_var,
  [1278] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 4,
      sym_false,
      sym_true,
      anon_sym_not,
      sym_const,
    ACTIONS(105), 9,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_EQ_GT,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      sym_var,
  [1299] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_DASH_GT,
    ACTIONS(111), 4,
      sym_false,
      sym_true,
      anon_sym_not,
      sym_const,
    ACTIONS(109), 8,
      anon_sym_DOT,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_EQ_GT,
      anon_sym_TILDE,
      sym_var,
  [1322] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_DASH_GT,
    ACTIONS(117), 4,
      sym_false,
      sym_true,
      anon_sym_not,
      sym_const,
    ACTIONS(115), 7,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_EQ_GT,
      anon_sym_TILDE,
      sym_var,
  [1344] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 4,
      sym_false,
      sym_true,
      anon_sym_not,
      sym_const,
    ACTIONS(115), 7,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BSLASH,
      anon_sym_EQ_GT,
      anon_sym_TILDE,
      sym_var,
  [1363] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_QMARK_DASH,
    ACTIONS(9), 1,
      sym_const,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    STATE(36), 1,
      aux_sym_source_file_repeat1,
    STATE(70), 1,
      sym__head,
    STATE(77), 5,
      sym__sentence,
      sym_typing_declaration,
      sym_clause,
      sym_fact,
      sym_query,
  [1389] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    ACTIONS(123), 1,
      anon_sym_QMARK_DASH,
    ACTIONS(126), 1,
      sym_const,
    STATE(36), 1,
      aux_sym_source_file_repeat1,
    STATE(70), 1,
      sym__head,
    STATE(77), 5,
      sym__sentence,
      sym_typing_declaration,
      sym_clause,
      sym_fact,
      sym_query,
  [1415] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(133), 1,
      anon_sym_COLON_COLON,
    ACTIONS(135), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym__atom,
    STATE(51), 1,
      aux_sym_typing_declaration_repeat1,
    STATE(65), 1,
      sym__parameters,
    ACTIONS(129), 2,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
    ACTIONS(137), 2,
      sym_const,
      sym_var,
  [1445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
    ACTIONS(141), 2,
      sym_const,
      sym_var,
    STATE(39), 2,
      sym__atom,
      aux_sym__parameters_repeat1,
  [1461] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
    ACTIONS(145), 2,
      sym_const,
      sym_var,
    STATE(40), 2,
      sym__atom,
      aux_sym__parameters_repeat1,
  [1477] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
    ACTIONS(149), 2,
      sym_const,
      sym_var,
    STATE(40), 2,
      sym__atom,
      aux_sym__parameters_repeat1,
  [1493] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 2,
      sym_type_i,
      sym_type_o,
    STATE(64), 2,
      sym__type,
      sym_type_arrow,
  [1508] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 2,
      sym_type_i,
      sym_type_o,
    STATE(63), 2,
      sym__type,
      sym_type_arrow,
  [1523] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(158), 2,
      sym_type_i,
      sym_type_o,
    STATE(68), 2,
      sym__type,
      sym_type_arrow,
  [1538] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(160), 2,
      sym_type_i,
      sym_type_o,
    STATE(33), 2,
      sym__type,
      sym_type_arrow,
  [1553] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 2,
      sym_type_i,
      sym_type_o,
    STATE(32), 2,
      sym__type,
      sym_type_arrow,
  [1568] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_body_repeat1,
    ACTIONS(45), 2,
      anon_sym_DOT,
      anon_sym_RPAREN,
  [1582] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym__expression_i,
    ACTIONS(167), 2,
      sym_const,
      sym_var,
  [1593] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_COMMA,
    ACTIONS(172), 1,
      anon_sym_COLON_COLON,
    STATE(48), 1,
      aux_sym_typing_declaration_repeat1,
  [1606] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      aux_sym__parameters_repeat2,
  [1619] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      sym__atom,
    ACTIONS(178), 2,
      sym_const,
      sym_var,
  [1630] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(180), 1,
      anon_sym_COLON_COLON,
    STATE(48), 1,
      aux_sym_typing_declaration_repeat1,
  [1643] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      anon_sym_QMARK_DASH,
      sym_const,
  [1652] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
    ACTIONS(184), 1,
      sym_var,
    STATE(14), 1,
      sym_typed_var,
  [1665] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
    ACTIONS(186), 1,
      sym_var,
    STATE(73), 1,
      sym_typed_var,
  [1678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(71), 1,
      sym__atom,
    ACTIONS(188), 2,
      sym_const,
      sym_var,
  [1689] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym__parameters_repeat2,
  [1702] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_DOT,
    STATE(46), 1,
      aux_sym_body_repeat1,
  [1715] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
    ACTIONS(194), 1,
      sym_var,
    STATE(78), 1,
      sym_typed_var,
  [1728] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LPAREN,
    ACTIONS(196), 1,
      sym_var,
    STATE(24), 1,
      sym_typed_var,
  [1741] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_body_repeat1,
  [1754] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      aux_sym__parameters_repeat2,
  [1767] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_COLON,
    ACTIONS(205), 1,
      anon_sym_EQ_GT,
  [1777] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_DASH_GT,
    ACTIONS(207), 1,
      anon_sym_DOT,
  [1787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_DASH_GT,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
  [1797] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 2,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
  [1805] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_COMMA,
      anon_sym_COLON_COLON,
  [1813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 2,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
  [1821] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_DASH_GT,
    ACTIONS(215), 1,
      anon_sym_DOT,
  [1831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
  [1839] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_DOT,
    ACTIONS(221), 1,
      anon_sym_COLON_DASH,
  [1849] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_COLON,
  [1864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
  [1871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
  [1878] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_const,
  [1885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_DOT,
  [1892] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_DOT,
  [1899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_EQ_GT,
  [1906] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      anon_sym_DOT,
  [1913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_EQ,
  [1920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_DOT,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 202,
  [SMALL_STATE(7)] = 260,
  [SMALL_STATE(8)] = 314,
  [SMALL_STATE(9)] = 368,
  [SMALL_STATE(10)] = 418,
  [SMALL_STATE(11)] = 470,
  [SMALL_STATE(12)] = 524,
  [SMALL_STATE(13)] = 576,
  [SMALL_STATE(14)] = 628,
  [SMALL_STATE(15)] = 677,
  [SMALL_STATE(16)] = 726,
  [SMALL_STATE(17)] = 775,
  [SMALL_STATE(18)] = 821,
  [SMALL_STATE(19)] = 864,
  [SMALL_STATE(20)] = 907,
  [SMALL_STATE(21)] = 950,
  [SMALL_STATE(22)] = 993,
  [SMALL_STATE(23)] = 1036,
  [SMALL_STATE(24)] = 1079,
  [SMALL_STATE(25)] = 1122,
  [SMALL_STATE(26)] = 1165,
  [SMALL_STATE(27)] = 1190,
  [SMALL_STATE(28)] = 1212,
  [SMALL_STATE(29)] = 1234,
  [SMALL_STATE(30)] = 1256,
  [SMALL_STATE(31)] = 1278,
  [SMALL_STATE(32)] = 1299,
  [SMALL_STATE(33)] = 1322,
  [SMALL_STATE(34)] = 1344,
  [SMALL_STATE(35)] = 1363,
  [SMALL_STATE(36)] = 1389,
  [SMALL_STATE(37)] = 1415,
  [SMALL_STATE(38)] = 1445,
  [SMALL_STATE(39)] = 1461,
  [SMALL_STATE(40)] = 1477,
  [SMALL_STATE(41)] = 1493,
  [SMALL_STATE(42)] = 1508,
  [SMALL_STATE(43)] = 1523,
  [SMALL_STATE(44)] = 1538,
  [SMALL_STATE(45)] = 1553,
  [SMALL_STATE(46)] = 1568,
  [SMALL_STATE(47)] = 1582,
  [SMALL_STATE(48)] = 1593,
  [SMALL_STATE(49)] = 1606,
  [SMALL_STATE(50)] = 1619,
  [SMALL_STATE(51)] = 1630,
  [SMALL_STATE(52)] = 1643,
  [SMALL_STATE(53)] = 1652,
  [SMALL_STATE(54)] = 1665,
  [SMALL_STATE(55)] = 1678,
  [SMALL_STATE(56)] = 1689,
  [SMALL_STATE(57)] = 1702,
  [SMALL_STATE(58)] = 1715,
  [SMALL_STATE(59)] = 1728,
  [SMALL_STATE(60)] = 1741,
  [SMALL_STATE(61)] = 1754,
  [SMALL_STATE(62)] = 1767,
  [SMALL_STATE(63)] = 1777,
  [SMALL_STATE(64)] = 1787,
  [SMALL_STATE(65)] = 1797,
  [SMALL_STATE(66)] = 1805,
  [SMALL_STATE(67)] = 1813,
  [SMALL_STATE(68)] = 1821,
  [SMALL_STATE(69)] = 1831,
  [SMALL_STATE(70)] = 1839,
  [SMALL_STATE(71)] = 1849,
  [SMALL_STATE(72)] = 1857,
  [SMALL_STATE(73)] = 1864,
  [SMALL_STATE(74)] = 1871,
  [SMALL_STATE(75)] = 1878,
  [SMALL_STATE(76)] = 1885,
  [SMALL_STATE(77)] = 1892,
  [SMALL_STATE(78)] = 1899,
  [SMALL_STATE(79)] = 1906,
  [SMALL_STATE(80)] = 1913,
  [SMALL_STATE(81)] = 1920,
  [SMALL_STATE(82)] = 1927,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exists, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_i, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eq, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eq, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_arrow, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_arrow, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_var, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typed_var, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__head, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 0),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typing_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typing_declaration_repeat1, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__parameters_repeat2, 2, 0, 0), SHIFT_REPEAT(55),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__parameters_repeat2, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typing_declaration, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__head, 2, 0, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typing_declaration, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__parameters, 4, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fact, 1, 0, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [225] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_existential_body, 3, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 3, 0, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_horn(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
